name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        twisted: ["tw21.2.0", "tw25.5.0", "twtrunk"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox codecov
        tox --notest -e coverage-${{ matrix.twisted }}

    - name: Test
      run: |
        python --version
        tox -e coverage

    - name: Upload Coverage
      run: codecov
